### ISSUE TITLE
Check for install.m

### ISSUE THREAD

**Issue by mobeets** [mobeets/mpm#21] opened 2017-09-12 15:27 UTC
After installation, check for and run any included installation file, e.g., one called `install.m`. (See #20 )

Should we check for a specifically named install file, such as `mpminstall.m`? Depends what sorts of things would be done inside an install script.

**Comment by mobeets** [comment] 2017-09-13 14:04
Okay, sounds good. Though this makes me think that having an "mpm uninstall" command might suggest that an "uninstall.m" file is being run.

Maybe we could call this file "setup.m" instead? Or maybe I should clarify what sort of things you think will be done in this install file?

**Comment by foosa** [comment] 2017-12-07 07:59
Looks like #44 is a partial duplicate of this enhancement.

**Comment by bendichter** [comment] 2018-07-26 15:53
I like this idea and I like `install.m`. I think `setup.m` might get confused as being analogous to `setup.py` which it sounds like it's not.

**Closed** 2018-07-29 19:33 UTC
Labels: enhancement
